cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
  - vendor/

.job-template: &job-template
  stage: test
  before_script:
  - pecl install xdebug
  - docker-php-ext-enable xdebug
  # Install composer dependencies
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - php composer.phar install
  # Install Xdebug
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  only:
  - master
  script:
  - ./vendor/bin/phpunit --coverage-text --colors=never
  - ./vendor/bin/phpstan analyze --ansi --level=max ./src
  artifacts:
    paths:
    - tests/_output/coverage
    expire_in: 1 month

# We test PHP7.1
test:PHP-7.1:
  <<: *job-template
  image: php:7.1
  only:
  - php7
  except:
  - master

# We test PHP7.2
test:PHP-7.2:
  <<: *job-template
  image: php:7.2
  only:
  - php7
  except:
  - master

# We test PHP7.3
test:PHP-7.3:
  <<: *job-template
  image: php:7.3
  only:
  - php7
  except:
  - master
